### ISSUE TITLE
release.useLastTag should not use lastTag unless current commit has that tag

### ISSUE THREAD

**Issue by rahulsom** [nebula-plugins/nebula-release-plugin#114]
This is my commit log

```
* c492218 (HEAD -> master, origin/master) 🐶
* 9467305 🐈
* 2f5d09e 🍌
* 00df6e7 (tag: v0.2.3) 🍎
```

My CI system accidentally built `c492218` with `./gradlew --stacktrace -Prelease.useLastTag=true clean check devSnapshot`

That resulted in `c492218` being built and artifacts generated from `c492218` being published as `0.2.3` in my maven repository.

----

A more reasonable behavior for `release.useLastTag` should be

_If there is a tag on the current commit, use that. If not, error out_.

**Comment by sghill** [comment]
Additionally, the release tasks should fail if attempting to produce a version that does not fit the scheme (example: candidates must end in `-rc.#`)

**Comment by Majkom** [comment]
What about merge commits? Because of compliance regulations I have 1st candidate branch where I build candidate version and it generates rc tag. Then I am merging it to 2nd candidate branch where I have useLastTag=true policy to reuse the same tag while pushing artefacts. But from git perspective my recent commit is a merge-commit and it has no tags. After change described above  my CI fails. Any hints how to overwrite this breaking change?
