### ISSUE TITLE
How to change default strategy for project version?

### ISSUE THREAD

**Issue by artemptushkin** [nebula-plugins/nebula-release-plugin#149]
Copied from my [stackoverflow](https://stackoverflow.com/questions/56507978/how-to-change-default-strategy-for-project-version) question

---
I need my artifact to be built with `project.version` equals to snapshot git based version.

For example, default version after `clean build` or idea build:
`0.2-dev.#hash`

I need: `1.1-SNAPSHOT` where 1.1 is from git tag, like when I run `snapshot` task

I tried to change [ReleasePluginExtension.groovy][1]:
```
release {
    defaultVersionStrategy = Strategies.SNAPSHOT
}
```
And
```
release {
    versionStrategy(Strategies.SNAPSHOT)
}
```
Doesn't work

My current workaround to set project.version inside by build.gradle like in library code - create object of snapshot strategy and call #version() method:
```
release {
    def gitRoot = project.hasProperty('git.root') ? project.property('git.root') : project.rootProject.projectDir
    def git = Grgit.open(dir: gitRoot)
    project.version = Strategies.SNAPSHOT.infer(project, git).version()
}
```
But i think it should be customizable by nebula-plugin.

  [1]: https://github.com/nebula-plugins/nebula-release-plugin/blob/9050b9719e494778c3b6d129bcbdc6a1c92b7648/src/main/groovy/nebula/plugin/release/git/base/ReleasePluginExtension.groovy

**Comment by chali** [comment]
Hi @artemptushkin the first attempt is the right idea:
```
release {
    defaultVersionStrategy = Strategies.SNAPSHOT
}
```
The tricky part is that you cannot touch the project version before Gradle has a chance to finish the configuration. I was looking at our projects and this set of `defaultVersionStrategy` is too late because of another plugin reading version too soon. You can look if that is under your control and move `project.version` to `afterEvaluate` so configuration can be finished.

Another maybe slightly better workaround is to set manually release stage. The plugin determines the stage based on the invoked task. You can do `-Prelease.stage=SNAPSHOT` which will force the SNAPSHOT strategy. However, you cannot set it when you do releases. Again you will probably not be able to do that in `build.gradle` because it would be too late.

**Comment by artemptushkin** [comment]
@chali thank you, I have some kind of hypothesis that maybe it is too late. I'll try some workarounds and leave success here - someone can be needed. If I don't - close the issue in a month.
