### ISSUE TITLE
Gitlab  integration

### ISSUE THREAD

**Issue by jvmlet** [nebula-plugins/nebula-release-plugin#181]
Hello
We have successfully implemented release strategy using `nebula-release-plugin` with our in-house hosted gitlab instance.  Few months ago  after upgrade, Gitlab decided to fetch only 50  latest changes  when running the runner's job:

````
Fetching changes with git depth set to 50...
````
Our `v1.0.0` release tag  is 58 commits  behind, and running `gradlew snapshot` infers version `0.1.0-SNAPSHOT` instead of  `1.1.0-SNAPSHOT`.

Please advise
Thanks

**Comment by jvmlet** [comment]
The ugly workaround we have so far is to define `GIT_DEPTH` environment variable with value of `10000000`. May be someone has more robust solution.

**Comment by rpalcolea** [comment]
Hi, I don't think there is a solution on nebula side since this is an implementation detail of your ci server, in this case gitlab pipelines.

If you don't need snapshots and you only require to calculate candidates or releases, you can always rely on tagging things yourself, for example:

```
git tag v1.0.0
./gradlew -Prelease.useLastTag=true final
``` 

you could tag via git or ui and then have your ci/cd pipeline being triggered by the event and use the last tag as the one for the final release.

Looking at your original issue, since you are using snapshots, I think your best bet is to modify the `GIT_DEPTH`, probably a lower number though, based on your commit activity. You could also analyze your git history and see if you could squash commits every once in a while but that's really a big change in the history

**Comment by jvmlet** [comment]
Thanks for your input @rpalcolea , I will stay with `GIT_DEPTH` approach. 
I think it might be worth to check if `grgit` provides API to query **remote** tags/branches in addition to local...
