### ISSUE TITLE
Need to be able to exclude some modules from nebula

### ISSUE THREAD

**Issue by jimshowalter** [nebula-plugins/nebula-release-plugin#182]
Per https://github.com/nebula-plugins/nebula-release-plugin/issues/33, the nebula release plugin has to be applied at the root. Which is fine, except we have a multi-module repo consisting of a mix of shared libraries and micro-services, and the micro-services aren't published at all--they're *deployed*, in built images. So we need a way to nebulize the shared libraries, while leaving the service modules alone. Adding versions to the services' jars screws up their Buildfiles and Dockerfiles, because those assume unversioned jars, and we wind up having to add a hack in the Jenkinsfiles to punch out to bash just to cp build/libs/service*jar build/libs/service.jar.

**Comment by jimshowalter** [comment]
Or even leaving aside mixing service with libraries, there's an entire other reason to allow modules to be excluded: some of them might just be reusable code within the repo that is not intended for public consumption.

**Comment by chali** [comment]
Hi @jimshowalter I understand the reasons behind this request. Unfortunately, the plugin is opinionated in this direction because at Netflix we only one service or one library in one gradle project so we don't plan to implement such a thing at this moment. You should be able to wrap nebula-release in your own plugin and implement it. Nebula-release just orchestrates the release. You could provide custom configuration and control whether each module will actually invoke the publishing step or not.

**Comment by jimshowalter** [comment]
Fair enough. If you ever discover a need to exclude modules, you have an alpha/beta tester.
