### ISSUE TITLE
Version not calculated correctly from release candidates

### ISSUE THREAD

**Issue by nadavc** [nebula-plugins/nebula-release-plugin#36]
Scenario 1: do a `./gradlew candidate` and then a simple `./gradlew version`. You'll see that the inferred version is something like `2.1.0-rc.2.dev.0+0faf0e7` instead of `2.1.0-rc.2.0+0faf0e7`

Scenario 2: do a `./gradlew candidate` and then a `./gradlew devSnapshot`. The snapshot released will be `2.1.0-rc.2.dev.0+0faf0e7`. It would be better to either advance to the next version (e.g.`2.2.0-dev.0+0faf0e7`) or fail the build until `./gradlew final` is called. 

Thoughts?

**Comment by rspieldenner** [comment]
I would expect a candidate producing `2.1.0-rc.2` and then a devSnapshot would return to `2.1.0-dev.#+hash`

**Comment by Krijger** [comment]
You can get this to work with https://github.com/nebula-plugins/nebula-release-plugin#releasing-using-last-tag

My workflow (see https://github.com/stackwork/stackwork for sources) is that I run `./gradlew candidate` locally, which pushes a git tag to my repository. Then (and you could of course also do this locally), the build script run by Travis does `./gradlew -Prelease.useLastTag=true candidate publishPlugins`, resulting in the expected release.

**Comment by Krijger** [comment]
Hmm, I was confused by the answer of @rspieldenner .

> I would expect a candidate producing 2.1.0-rc.2

That is actually the case right? Because, if you print the project version during a `candidate` build, using

    task('version') << {
      println ('VERSION: ' + project.version)
    }
    tasks.version.dependsOn project.tasks.prepare

and `./gradlew candidate version` you get `2.1.0-rc.2`. Also, running `./gradlew candidate` and then `./gradlew -Prelease.useLastTag=true version` will produce the same.

Removing "dev" from

> 2.1.0-rc.2.dev.0+0faf0e7 instead of 2.1.0-rc.2.0+0faf0e7

doesn't do much I would say. You're developing on the release candidate, which is perfectly valid - otherwise you would have done a `final` release. I would definitely not fail the build until `./gradlew final` is called, because you might want to have people test these final bugfixes you're working on. Nor would I advance to the next version, because you are working towards the final 2.1.0 release. @rspieldenner may have a point in saying you could change `rc.2.dev....` to `dev....` again, but the former does make clear you're working on a release candidate to create the final release.

**Comment by chrisbouchard** [comment]
One thing to keep in mind is that Gradle will sort

`1.0.0-dev.3...` < `1.0.0-rc.2.dev.3...` < `1.0.0-rc.2`

They explicitly enforce that `dev` < `rc`, and adding a non-numeric tag is less than not adding a non-numeric tag. ([It's documented in JavaDoc.](https://github.com/gradle/gradle/blob/master/subprojects/core-api/src/main/java/org/gradle/api/artifacts/VersionConstraint.java#L55))

So, it would be very handy for local development if, `devSnapshot` after `candidate` produced something like `1.0.0-rc.2.3...` or something like that. That way, local development can continue between release candidates, and Gradle will resolve versions in a sane manner.

**Comment by rpalcolea** [comment]
This should be fixed now in 12.0.0.

More details in https://github.com/nebula-plugins/nebula-release-plugin/pulls?q=is%3Apr+is%3Aclosed

**Comment by edenlin18** [comment]
It seems https://github.com/nebula-plugins/nebula-release-plugin/pull/162 does not really cover what @nadavc originally asked for. As pointed out by @chrisbouchard, gradle always prioritize rc version, so ideally, the version needs to be bumped when a RC is cut so that current development can continue.
